title: Eggsample App Status
languageCode: fr
baseURL: /
params:
  # https://github.com/mistermantas/cstate/wiki/Customization
  systems:
    -
      name: Gateway
    -
      name: API
      description: The guts of the application.
    -
      name: Media Proxy
      description: This is the service responsible for serving images, audio, and video. It is reliant on our CDN.

  useLargeHeaderDesign: false
  useLogo: true
  logo: /logo.png
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.
  # customTabs:
  #  -
  #    name: Name
  #    link: https://example.com

  autoRefresh: true
  incidentPostsPerPage: 10

  brand: 181818
  ok: 228B22
  disrupted: FF8C00
  down: DC143C
  notice: 708090
  alwaysKeepBrandColor: true

  googleAnalytics: UA-00000000-1

buildFuture: true
theme: cstate
version: 2
